name: Sample Workflow
on:
  push:

jobs:
  sample-job:
    runs-on: ubuntu-latest
    steps:
      - name: Testing
        run: |
          echo "Hello"
          date
          echo ${{ github.event.head_commit.message }}
