# Creates a dev release and pushes it to firebase distribution

name: Commit and skip
on: workflow_dispatch

jobs:
  commit_and_skip:
    name: Commit and skip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT }}
      - name: Configure CI Git User
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'gh-actions@example.com'
      - name: Working skipper
        shell: bash
        run: |
          date >> README.md
          git add README.md
          git commit -m $'This works and does not trigger the ci workflow [skip ci]'
          git push origin ${{ github.head_ref }}
      - name: Not working skipper
        shell: bash
        run: |
          date >> README.md
          git add README.md
          git commit -m $'This doesn't work and will trigger the ci workflow\n\n\nskip-checks:true'
          git push origin ${{ github.head_ref }}
