# Creates a dev release and pushes it to firebase distribution

name: Commit and skip
on: workflow_dispatch

jobs:
  commit_and_skip:
    name: Commit and skip
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure CI Git User
        run: |
          git config --global user.name 'Github Actions'
          git config --global user.email 'gh-actions@example.com'
      - name: Push changes
        shell: bash
        run: |
          date >> README.md
          git add README.md
          git commit -m $'This commit should not trigger the ci workflow'
          git push origin ${{ github.head_ref }}
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ci.yml',
              ref: 'main',
            })
